stages:
  - buildBackend
  - buildFrontend
  - tests
  - deploy
buildBackend:
  stage: buildBackend
  script:
    - cd Backend/
    - ng serve
  only:
    - production
  tags:
    - docker
tests:
  stage: tests
  script:
    - cd Backend/
    - npm test
deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt-get update
  only:
    - production
  tags:
    - docker