stages:
  - build
  - deploy
build:
  stage: build
  script:
    - echo "test"
deploy:
  stage: deploy
  script:
    - cd Backend/
    - apt-get update
    - apt-get install -y -qq npm
    - npm install
    - npm start
  environment:
    name: production
    url: https://51.254.103.142
  only:
  - master