stages:
  - build
  - tests
  - deploy
build:
  stage: build
  script:
    echo "fails but tests run, why :("
  environment:
    name: production
    url: https://51.254.103.142
  only:
  - 36-fix-gitlab-ci-yml
tests:
  stage: tests
  script:
    - cd Backend/
    - npm install
    - npm run test
  environment:
    name: production
    url: https://51.254.103.142
  only:
  - 36-fix-gitlab-ci-yml
deploy:
  stage: deploy
  script:
    - cd Backend/
    - npm start
  environment:
    name: production
    url: https://51.254.103.142
  only:
  - 36-fix-gitlab-ci-yml