stages:
  - build
  - tests
  - deploy
build:
  stage: build
  script:
    echo "fails but tests run, why :("
tests:
  stage: tests
  script:
    - cd Backend/
    - npm install
    - npm run test
  environment:
    name: $CI_ENVIRONMENT_NAME
    url: $CI_ENVIRONMENT_URL
  only:
  - 36-fix-gitlab-ci-yml
deploy:
  stage: deploy
  script:
    - cd Backend/
    - npm start
  environment:
    name: $CI_ENVIRONMENT_NAME
    url: $CI_ENVIRONMENT_URL
  only:
  - 36-fix-gitlab-ci-yml