stages:
  - build
  - tests
  - deploy
build:
  stage: build
  script:
    - echo "test"
tests:
  stage: tests
  script:
    - apt-get update
    - apt-get install -y -qq nodejs npm
    - cd Backend/
    - npm install -g mocha
    - npm run test
deploy:
  stage: deploy
  script:
    - cd Backend/
    - npm start
  environment:
    name: production
    url: https://51.254.103.142
  only:
  - master